name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Validate model
        uses: committed-consulting/epsilon-ci-action@v2
        with:
          target: validate
      - name: Transform to MiniJava
        uses: committed-consulting/epsilon-ci-action@v2
        with:
          target: transform
      - name: Upload MiniJava Model
        uses: actions/upload-artifact@v3.1.3
        with:
          name: state-machine-java-model
          path: models/state-machine-java.xmi
      - name: Generate Java
        uses: committed-consulting/epsilon-ci-action@v2
        with:
          target: generate
      - name: Upload completed Gradle project
        uses: actions/upload-artifact@v3.1.3
        with:
          name: gradle-project
          path: gradle
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          build-root-directory: gradle
          arguments: build
