name: Weekly Epsilon 2.5.0 report

on:
  schedule:
    - cron: '5 4 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Epsilon 2.5.0 report
        uses: committed-consulting/epsilon-ci-action@v2
        with:
          target: generateEpsilonMilestoneReport
      - name: Upload Log
        uses: actions/upload-artifact@v3.1.3
        with:
          name: milestoneReport
          path: RELEASE_NOTES.md
