name: Build slides

on:
  push:
    branches:
      - main
    paths:
      - 'slides/**.md'
      - .github/workflows/slides.yml

jobs:
  pandoc-build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:3.1-ubuntu
      volumes:
        - /github/workspace:/data
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Generate HTML with Pandoc
        run: mkdir _site && pandoc -t revealjs -s slides/mde-ci-slides.md -o _site/index.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: pandoc-build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
